### ISSUE TITLE
开发建议

### ISSUE THREAD

**Issue by RinWinter1145** [Sodiumsss/maimai_queue_client#2]
我们城市有多台机子，能不能弄个多机排卡😭😭😭
就是在主页基础上加个机器选择，每台机子独立排卡，然后弄个不准多机排卡（防止某些rz多机排）
还有，怎么设置超管，管理啊😭😭😭

**Comment by Sodiumsss** [comment]
你好，SYSTEMWEBMONKEY。这个排卡页是很久以前用来练手做的，我不会更新这个仓库了，但是最近自己的网站正在更新排卡功能，在更新完毕之后，我应该会把排卡功能单独抽离出来做成一个独立系统的。
